---
namespace: bar
resources:
  - namespace.yaml
  - ../../base
nameSuffix: -bar
commonLabels:
  app.kubernetes.io/instance: bar

patches:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: echo
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: bar.localhost
